// Mocks generated by Mockito 5.4.5 from annotations
// in ft/test/features/forex_pairs/data/repository/forex_pairs_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ft/features/forex_pairs/data/data_source/forex_pairs_data_remote_source.dart'
    as _i2;
import 'package:ft/features/forex_pairs/data/mapper/forex_pair_mapper.dart'
    as _i5;
import 'package:ft/features/forex_pairs/data/response/forex_pair_reponse.dart'
    as _i4;
import 'package:ft/features/forex_pairs/domain/entity/forex_pair.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ForexPairsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForexPairsRemoteDataSource extends _i1.Mock
    implements _i2.ForexPairsRemoteDataSource {
  MockForexPairsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ForexPairResponse>> getForexPairs() =>
      (super.noSuchMethod(
            Invocation.method(#getForexPairs, []),
            returnValue: _i3.Future<List<_i4.ForexPairResponse>>.value(
              <_i4.ForexPairResponse>[],
            ),
          )
          as _i3.Future<List<_i4.ForexPairResponse>>);
}

/// A class which mocks [ForexPairMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockForexPairMapper extends _i1.Mock implements _i5.ForexPairMapper {
  MockForexPairMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.ForexPair> map(List<_i4.ForexPairResponse>? response) =>
      (super.noSuchMethod(
            Invocation.method(#map, [response]),
            returnValue: <_i6.ForexPair>[],
          )
          as List<_i6.ForexPair>);
}
