// Mocks generated by Mockito 5.4.5 from annotations
// in ft/test/features/ticker/data/repository/web_socket_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ft/features/ticker/data/data_source/web_socket_data_source.dart'
    as _i2;
import 'package:ft/features/ticker/data/mapper/ticker_list_mapper.dart' as _i4;
import 'package:ft/features/ticker/data/response/web_socket_response.dart'
    as _i6;
import 'package:ft/features/ticker/domain/entity/ticket_entity.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WebSocketDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketDataSource extends _i1.Mock
    implements _i2.WebSocketDataSource {
  MockWebSocketDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i3.Stream<dynamic>?> getStream() =>
      (super.noSuchMethod(
            Invocation.method(#getStream, []),
            returnValue: _i3.Future<_i3.Stream<dynamic>?>.value(),
          )
          as _i3.Future<_i3.Stream<dynamic>?>);

  @override
  _i3.Future<void> subscribe(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [symbol]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unSubscribe(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#unSubscribe, [symbol]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TickerListMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTickerListMapper extends _i1.Mock implements _i4.TickerListMapper {
  MockTickerListMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.TickerEntity> fromJson(_i6.WebSocketResponse? response) =>
      (super.noSuchMethod(
            Invocation.method(#fromJson, [response]),
            returnValue: <_i5.TickerEntity>[],
          )
          as List<_i5.TickerEntity>);
}
